name: Validate K8s Manifests
on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Runs kubeconform from a prebuilt container, no install needed
      - name: kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          args: >
            -summary -strict
            -schema-location default
            -schema-location https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/{{.NormalizedKubernetesVersion}}-standalone/{{.ResourceKind}}.json
            $(find k8s -type f -name '*.yaml' -o -name '*.yml')
